
name: 'SNOWFLAKE_DEVOPS'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
# seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  SNOWFLAKE_DEVOPS:
    staging:
      materialized: view
      snowflake_warehouse: compute_wh
    marts:
      materialized: table
      snowflake_warehouse: compute_wh