
name: test_run

on:
  push:
  pull_request:
    branches: [ "dev_branch" ]
env:
  DBT_PROFILES_DIR: ./
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASSWORD: ${{ secrets.SF_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/python@v4
        with:
          python-version: "3.8"
        
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requeirements.txt

      - name: Install dependencies
        run: |
          pip install dbt
          dbt deps
        
      - name: Run dbt models
        run: dbt run

      - name: Test dbt models
        run: dbt test          
